import { useEffect, useState } from 'react';
import axios from 'axios';

import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../../styles/Home.module.css';
import Profile from '../../components/profile';

const options = {
  'Content-Type': 'application/json',
}


export default function Home( ) {

    const [ posts , setPosts ] = useState([ ]);
    const [ postValue , updatePost ] = useState('');


    const fetchPosts = async ( ) => {
        // Always do navigations after the first render
        return await axios.get(`http://localhost:3000/api/ApiPosts/posts`);
    }


    const newPost = ( title ) => {
       axios.post(`http://localhost:3000/api/ApiPosts/posts`, { title }, options )
            .then( res => res.data )
            .then( data => {
                console.log( data );
            })
            .catch( err => console.log( err.response.data ) );
    }

    useEffect( async ( ) => {
        fetchPosts( )
            .then( res => res.data )
            .then( data => {
                console.log( data );
                setPosts( data );
            })
            .catch( err => console.log( ` err: ${ err }` ) );
    }, [ ] );
  

    return (
      <div className={styles.container}>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

            <Profile />

            <Link href={`/`}> 
                back to home
            </Link>
 
            <Link href={"/api/auth/login" }> login </Link>

            <div>
                  <input value={ postValue } onChange={ ( e ) => updatePost( e.target.value ) } />
                  <div onClick={ ( ) => newPost( postValue ) }> create post  </div>
            </div>

            <div>
                { posts.map(( post, index  ) =>
                    <div key={ index }>
                         
                         { post.userId }
                        <Link href={`/posts/${ post._id }`}> 
                            { post.title } 
                        </Link>
                    </div>
                )}
            </div>  
            
        </main>

        <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
        </footer>
        
      </div>
    )
}
